name: Build and deploy GH Pages

on: push

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Build
        run: make ci
      - name:  Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
